aliases: []
creation_timestamp: 1705182668633
current_stage: None
description: null
last_updated_timestamp: 1705182668633
name: log_reg_model
run_id: 9c857214c6854070b5d53f2e9418042b
run_link: null
source: /home/admin/mlflow/4/9c857214c6854070b5d53f2e9418042b/artifacts/train_model
status: READY
status_message: null
storage_location: /home/admin/mlflow/4/9c857214c6854070b5d53f2e9418042b/artifacts/train_model
user_id: null
version: 5
