aliases: []
creation_timestamp: 1705180934229
current_stage: None
description: null
last_updated_timestamp: 1705180934229
name: log_reg_model
run_id: 09a3a06c305b4e2292716a82b3e1f4e0
run_link: null
source: /home/admin/mlflow/4/09a3a06c305b4e2292716a82b3e1f4e0/artifacts/train_model
status: READY
status_message: null
storage_location: /home/admin/mlflow/4/09a3a06c305b4e2292716a82b3e1f4e0/artifacts/train_model
user_id: null
version: 2
